---

defaults: &defaults
  working_directory: /tmp
  docker:
    - image: docker:stable-git

version: 2

jobs:
  test:
    <<: *defaults
    environment:
      GOSS_FILES_STRATEGY: cp

    steps:
      - checkout:
          path: /tmp/workspace

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t tiddlywiki .
            docker save tiddlywiki | gzip -c > tiddlywiki.tar.gz
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache --no-progress bash curl
            curl -fsSL https://goss.rocks/install | sh
      - run:
          name: Test Docker image
          command: |
            cd tests/
            dgoss run tiddlywiki --server

      - persist_to_workspace:
          root: workspace
          paths:
            - tiddlywiki.tar.gz

  tag:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache --no-progress bash
      - run:
          name: Tag Docker image
          command: |
            docker load --input /tmp/workspace/tiddlywiki.tar.gz
            PATCH_VERSION=$(docker run -it --rm tiddlywiki --version)
            MAJOR_VERSION=${PATCH_VERSION%%.*}
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker tag tiddlywiki "elasticdog/tiddlywiki:latest"
            docker tag tiddlywiki "elasticdog/tiddlywiki:${PATCH_VERSION}"
            docker tag tiddlywiki "elasticdog/tiddlywiki:${MAJOR_VERSION}"
            docker image ls elasticdog/tiddlywiki
            echo docker push elasticdog/tiddlywiki

workflows:
  version: 2
  build:
    jobs:
      - test
      - tag:
          requires:
            - test
          filters:
            branches:
              only:
                - master
