version: 2

jobs:
  test:
    docker:
      - image: docker:stable-git

    environment:
      GOSS_FILES_STRATEGY: cp

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            cd 5/
            docker build -t tiddlywiki .

      - run:
          name: Install testing dependencies
          command: |
            apk add --no-cache --no-progress bash curl
            curl -fsSL https://goss.rocks/install | sh

      - run:
          name: Test Docker image
          command: |
            cd tests/
            dgoss run tiddlywiki --server

  tag:
    docker:
      - image: docker:stable

    steps:
      - setup_remote_docker

      - run:
          name: Push version-specific image tag
          command: |
              echo "docker login -u $DOCKER_USER -p $DOCKER_PASS"
              echo "docker tag ${DOCKER_USER}/tiddlywiki:5 ${DOCKER_USER}/tiddlywiki:$(docker run -it --rm ${DOCKER_USER}/tiddlywiki:5 --version)"

workflows:
  version: 2

  test_and_tag:
    jobs:
      - test
      - tag:
          requires:
            - test
          filters:
            branches:
              only: master
