---

# yaml anchor to reduce duplication
tiddlywiki_major_version: &tiddlywiki_major_version
  MAJOR_VERSION: 5

version: 2

jobs:
  test:
    docker:
      - image: docker:stable-git

    environment:
      GOSS_FILES_STRATEGY: cp
      <<: *tiddlywiki_major_version

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            cd $MAJOR_VERSION/
            docker build -t tiddlywiki .

      - run:
          name: Install testing dependencies
          command: |
            apk add --no-cache --no-progress bash curl
            curl -fsSL https://goss.rocks/install | sh

      - run:
          name: Test Docker image
          command: |
            cd tests/
            dgoss run tiddlywiki --server

  tag:
    docker:
      - image: docker:stable

    environment:
      <<: *tiddlywiki_major_version

    steps:
      - setup_remote_docker

      - run:
          name: Add patch version tag to major version image
          command: |
            PATCH_VERSION=$(docker run -it --rm tiddlywiki --version)
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker pull "${DOCKER_USER}/tiddlywiki:${MAJOR_VERSION}"
            docker tag "${DOCKER_USER}/tiddlywiki:${MAJOR_VERSION}" "${DOCKER_USER}/tiddlywiki:${PATCH_VERSION}"
            echo docker push "${DOCKER_USER}/tiddlywiki:${PATCH_VERSION}"

workflows:
  version: 2

  push:
    jobs:
      - test

  daily:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tag
